### ISSUE TITLE
[Task] 남태식 / landing page, contents page 디자인 

### ISSUE THREAD

**Issue by Southbig** [codestates/AllForYou#176]
### ISSUE
* Group: client
* Type: feature
* Detail: 렘딩페이지 디자인, 컨텐츠페이지 반응형 재배치
### TODO
- [x] 렌딩페이지 1 (첫번째로 보여지는 화면), all for you 소개
- [x] 렘딩페이지 2 컨텐츠 페이지 소개
- [x] 컨텐츠페이지 반응형 재배치

### Labels
- Group : `client`
