### ISSUE TITLE
[Task] 강사름 / 랜딩페이지 및 부가 기능 구현

### ISSUE THREAD

**Issue by sarumi-k** [codestates/AllForYou#196]
### ISSUE
* Group: client
* Type: feature
* Detail: foru 메인 좋아요 구분 구현, 컨텐츠 리스트 모달 적용, 랜딩페이지 디자인 및 애니메이션 구상

### TODO
- [x] foru main - 회원에 따른 좋아요 구분
- [x] foru view - 추천리스트의 컨텐츠 클릭 시, 모달 구현
- [x] landing page - foru 페이지에 대한 부분 우선 시작
- [x] 컨텐츠 공유하기 - url, 카톡 공유하기 기능 구현

### Labels
- Group : `client`
- Urgency: `Middle`, `Low`
