### ISSUE TITLE
[Task] 강사름 / 랜딩 페이지 레이아웃 및 기능 구현

### ISSUE THREAD

**Issue by sarumi-k** [codestates/AllForYou#233]
### ISSUE
* Group: client
* Type: feature
* Detail: for u 랜딩 페이지 두 번째 디자인 및 기능 구현, for u 랜딩 페이지 첫 번째 오류 수정
* 
### TODO
- [x] 랜딩 첫 페이지 화살표 오류 수정
- [x] 랜딩 첫 페이지 클릭 이벤트 삭제 또는 추가 필요
- [x] 랜딩 두번째 페이지 디자인
- [x] 랜딩 두전때 페이지 기능 구현

### Labels
- Group : `client`
- Urgency: `Middle`, `Low`
