### ISSUE TITLE
[Task] 홍세환/Client

### ISSUE THREAD

**Issue by HongSehwan** [codestates/AllForYou#37]
### ISSUE
* Group: client
* Type: feature
* Detail: Client Login page, SIgnUp page, MyPage development

### TODO
- [x] Login page (JSX, CSS) development
- [x] SIgnUp page (JSX, CSS) development
- [x] MyPage (JSX, CSS) development

### Labels
- Group : `client`
- Sprint: `AllForYou`
- Urgency: `Middle`
