### ISSUE TITLE
[Task] 이재영 / server

### ISSUE THREAD

**Issue by dlwodud9529** [codestates/AllForYou#38]
### ISSUE
* Group: server
* Type: feature
* Detail: 서버 초기작업

### TODO
- [x] index.js 서버파일 제작
- [x] sequlize를 이용한 DB 생성
- [x] 라우팅 테이블 작성
- [x] users 기능구현(로그인, 로그아웃, 회원정보 수정, 회원탈퇴, 유저정보 불러오기)
- [x] 서버 실행해보기
- [x] 더미파일 생성, FK 연결을 통한 CASCADE 확인
- [x] 회원가입 시 이메일 발송

### Labels
- Group : `server`
- Urgency: `Middle`, `Low`
