### ISSUE TITLE
[Task] 남태식 / contents page_modal window moke up 

### ISSUE THREAD

**Issue by Southbig** [codestates/AllForYou#42]
### ISSUE
* Group: client
* Type: feature
* Detail: 컴텐츠페이지 모달창 moke up, 컨텐츠페이지 API 선정 논의, 랜딩페이지 아이디어 논의, 설문조사 진행 논의 (1/3)
* Detail: contents page 선택에 따른 UI 재배치 (1/4)
* Detail: 케로셀 적용 및 레이아웃 재배치 (1/5)
### TODO
- [x] 컨텐츠페이지 모달창 moke up (1/3)
- [x] 컨텐츠페이지 API 선정 논의 (1/3)
- [x] 랜딩페이지 아이디어 논의 (1/3)
- [x] 설문조사 진행 방향 논의 (1/3)
- [x] 컨텐츠페이지 전체 moke up (선택에 따른 UI 재배치) (1/4)
- [x] 케로셀 적용 및 레이아웃 재배치 (1/5)

### Labels
- Group : `client`
- Urgency: `High`
