### ISSUE TITLE
[Task] 홍세환/Contents

### ISSUE THREAD

**Issue by HongSehwan** [codestates/AllForYou#45]
### ISSUE
* Group: server
* Type: feature
* Detail: Server add contents page

### TODO
- [x] Server contents page development
- [x] Server fix database contents data from migration, model
- [x] Server add server database contents seeders file

### Estimated time
> Pick one
```4h```

### Labels
- Estimated time: `E: 4h`
- Group : `server`
- Sprint: `AllForYou`
- Urgency: `Middle`
