### ISSUE TITLE
[Task] 남태식 / 케로셀 버튼 변경, 컨텐츠페이지 반응형 적용, 이미지 선택시 모달창 활성화 및 정보 전달

### ISSUE THREAD

**Issue by Southbig** [codestates/AllForYou#46]
### ISSUE
* Group: client
* Type: bug, feature
* Detail: 케로셀 버튼 변경, 컨텐츠페이지 반응형 적용, 이미지 선택시 모달창 활성화 및 정보 전달

### TODO
- [x] 케로셀 버튼 변경
- [x] 컨텐츠페이지 반응형 적용
- [x] 이미지 선택시 모달창 활성화 및 정보 전달

### Estimated time
> 케로셀 버튼 변경
```3h```

> 컨텐츠페이지 반응형 적용
```3h```

> 이미지 선택시 모달창 활성화 및 정보 전달
```2h```

### Labels
- Estimated time: `E: 8h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
