### ISSUE TITLE
[Task] 강사름 / nav, footer, forUpage 목업

### ISSUE THREAD

**Issue by sarumi-k** [codestates/AllForYou#51]
### ISSUE
* Group: client
* Type: feature
* Detail: nav, footer, forUpage 목업 진행

### TODO
- [ ] navbar 목업
- [ ] footer 목업
- [ ] forUpage 목접
- [ ] forUpage 내부에서 연결되는 writing Page, view Page 목업
- [ ] writing Page 글쓰기에 quill 라이브러리 적용
- [ ] 내부 페이지 navigate 적용 연결

### Labels
- Group : `client`
- Urgency: `Low`
