### ISSUE TITLE
[Task] 강사름 / forUpage 관련 component 구현

### ISSUE THREAD

**Issue by sarumi-k** [codestates/AllForYou#53]
### ISSUE
* Group: client
* Type: feature
* Detail: forUpage 관련 component 구현, DB 정보 검색

### TODO
- [ ] comment component 목업
- [ ] recommend component 목업
- [ ] 글쓰기 페이지 image 기능 구현
- [ ] 글쓰기 페이지 검색 기능 구현
- [ ] DB용 정보 검색(슬픔, 웃음)

### Labels
- Group : `client`
- Urgency: `Low`
