### ISSUE TITLE
[Task] 남태식 /  모든 이미지 클릭시 모달창 구현,  검색 기능, 좋아요 기능 알아보기,  배경색 적용 및 , 여러가지 스타일링 해보기,  반응형 재 구성

### ISSUE THREAD

**Issue by Southbig** [codestates/AllForYou#55]
### ISSUE
* Group: client
* Type: feature
* Detail: 모든 이미지 클릭시 모달창 구현,  검색 기능, 좋아요 기능 알아보기,  배경색 적용 및 , 여러가지 스타일링 해보기,  반응형 재 구성, 컨텐츠 찾기

### TODO
- [x]  모든 이미지 클릭시 모달창으로 상세페이지 구현
- [ ]  검색 기능, 좋아요 기능 알아보기 및 적용
- [ ]  배경색 적용, 컴포넌트 강조색 적용 (여러가지 스타일링 해보기)
- [x]  카테고리, 컨텐츠 선택 페이지 반응형 재 구성
- [x] 컨텐츠 데이터 찾기

### Estimated time
> 모든 이미지 클릭시 모달창으로 상세페이지 구현
```1h```
> 검색 기능, 좋아요 기능 알아보기 및 적용 및 백엔드 조율
```3d```
> 배경색 적용, 컴포넌트 강조색 적용 (여러가지 스타일링 해보기)
```3d```
> 카테고리, 컨텐츠 선택 페이지 반응형 재 구성
```2h```
>컨텐츠 데이터 찾기
```3h```

### Labels
- Estimated time: `E: 10h`
- Group : `client`
- Urgency: `Middle`
