### ISSUE TITLE
[Task] 이재영/client 요청 확인, 응답코드 작성 외 2

### ISSUE THREAD

**Issue by dlwodud9529** [codestates/AllForYou#57]
### ISSUE
* Group: server
* Type: feature
* Detail: 라우팅 테이블에 있는 파일 생성, 응답코드 작성

### TODO
- [x] review내용 클라이언트에 전달하기 위한 코딩작업
- [x] 라우팅 테이블에 적힌 파일들 생성 및 응답코드 작성
- [x] DB에 넣을 데이터 찾기

### Labels
- Group : `server`
- Urgency: `Low`
