### ISSUE TITLE
[Task] 강사름 / writing page 기능 구현

### ISSUE THREAD

**Issue by sarumi-k** [codestates/AllForYou#59]
### ISSUE
* Group: client
* Type: feature
* Detail: writing page 기능 구현, DB 정보 백색소음 찾기

### TODO
- [x] 컨텐츠 검색 완료되면 체크 된 목록 추가 기능 구현
- [x] 추가된 목록 체크 후 삭제 기능 구현(장바구니 기능 참고 예정)
- [x] '등록' 클릭 시, 모든 내용 필수 입력 확인 후 POST 보내는 코드 구현
- [x] '취소' 클릭 시, ForU 리스트 페이지 이동 구현
- [x] FormData 구현 추가 확인
- [x] 백색소음 정보 수집

### Labels
- Group : `client`
- Urgency: `Low`
