### ISSUE TITLE
[Task] 남태식 / 기능, 디자인, 레이아웃 재배치, 기능 redux 로 재배치

### ISSUE THREAD

**Issue by Southbig** [codestates/AllForYou#64]
### ISSUE
* Group: client
* Type: feature
* Detail:
- 검색기능
- 좋아요기능
- 카테고리, 컨텐츠 선택 시 최신순, 좋아요순 정렬
- 페이지 디자인 적용
- 상세 모달 
  - 소제목 추가하여 레이아웃 재배치
  - 내용 설명에 스크롤 생성

### TODO
- [ ] 검색기능
- [ ] 좋아요기능
- [ ] 카테고리, 컨텐츠 선택 시 최신순, 좋아요순 정렬
- [x] 페이지 디자인 적용 (3안이 나왔지만 반응형 수정할때 다시 진행 예정)
- [x] 상세 모달 / 소제목 추가하여 레이아웃 재배치
- [x] 상세 모달 / 내용 설명에 스크롤 생성
- [x]  기능 리덕스로 재배치

### Labels
- Group : `client`
- Urgency: `High`, `Middle`
