### ISSUE TITLE
[Task] 강사름 / Foru page 기능 구현 및 반응형 추가

### ISSUE THREAD

**Issue by sarumi-k** [codestates/AllForYou#74]
### ISSUE
* Group: client
* Type: feature
* Detail:  Foru page 기능 구현 및 writing page 반응형 추가

### TODO
- [x] writing page 반응형 추가
- [x] navbar, footer 반응형 추가
- [x] Foru page - DB에서 리스트 작성 글 가져와서 정렬하기
- [x] Foru page - 글의 카테고리와 게시판 카테고리를 연결하여 정렬하기
- [x] Foru page - '좋아요' 순으로 정렬하기
- [ ] Foru page - 'URL', '카톡' 공유하기
- [x] Foru page - 글 클릭 시, 상세 페이지로 넘어가기

### Labels
- Group : `client`
- Urgency: `Low`
