### ISSUE TITLE
[Task] 강사름 / foruview page 기능 구현 및 반응형 추가

### ISSUE THREAD

**Issue by sarumi-k** [codestates/AllForYou#91]
### ISSUE
* Group: client
* Type: feature
* Detail:  foruview page 기능 구현 및 반응형 추가

### TODO
- [x] foruview page - 더미로 정보 넘어오는지 확인
- [x] foruview page - get axios 코드 구현
- [x] foruview page - '좋아요' 누르는 기능 구현
- [x] foruview page - 컨텐츠 정보 가져오는 기능 구현
- [x] foruview page - 댓글 등록 기능 구현
- [x] foruview page - 댁글 업데이트 기능 구현
- [x] foruview page - 댓글 삭제 기능 구현
- [ ] foruview page - 글 수정 기능 구현
- [x] foruview page - 반응형 구현

### Labels
- Group : `client`
- Urgency: `Low`
