### ISSUE TITLE
[Task] 남태식 / contents page 서버연동기능 확인

### ISSUE THREAD

**Issue by Southbig** [codestates/AllForYou#93]
### ISSUE
* Group: client
* Type: feature
* Detail: contents page 서버 연동 및 기능 구현

### TODO
- [x] contents page contents 데이터 가져오기
- [x] contents page 엔드포인트 별로 select 1, select2 선택시 분기 
- [x] contents page 좋아요, 최신순 분기 
- [x] contents page 검색 기능
- [x] contents page modal 좋아요 기능
- [x] contents page 스타일 재구성

### Labels
- Group : `client`
- Urgency: `Middle`
